name: Deploy to Heroku

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      go-version: 1.19

  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: heroku/api:${{github.sha}}
        
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "golang-cicd-workflow"
        heroku_email: "caiow.wk@gmail.com"
        healthcheck: "https://golang-cicd-workflow.herokuapp.com/health"
        # checkstring: "ok"
        delay: 5
        rollbackonhealthcheckfailed: true
        usedocker: true
        docker_build_args: |
          NODE_ENV
      env:
        NODE_ENV: production
