name: Test

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        required: false
        type: string
        default: '1.18'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "${{ inputs.go-version }}" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...